# Generated by Django 3.2.15 on 2022-10-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('index2', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('item_ids', models.IntegerField(blank=True, null=True)),
                ('clicked_ids', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rec',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='rec_app',
        ),
    ]
